### ISSUE TITLE
merge_generated_metadata.py Timestamp and Work_Flow options

### ISSUE THREAD

**Issue by JeanKRodriguez** [BD2KGenomics/dcc-metadata-indexer#39]
Add flags so that users can choose to make Timestamps or Workflow_version the option that will determine which is the best analysis_type to add into the schema, when there are duplicates.

**Comment by briandoconnor** [comment]
Ya, I think the most generic is to say, for that analysis_type and workflow_name, just choose the most recent timestamp'd workflow analysis event for inclusion in the index.  An alternative, based on what flag you give it, would look at the analysis_type, workflow_name, and most recent workflow_version and only use timestamp if there are multiple identical analysis_type, workflow_name, and workflow_version.
